# Generated by Django 6.0.7 on 2026-08-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(unique=True)),
                ("channel_id", models.TextField(unique=True)),
                ("title", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активен"), ("inactive", "Не активен")],
                        default="active",
                    ),
                ),
            ],
        ),
    ]
